=== opra-project/OPRA/schemas/eq_info.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "EQ Info",
  "description": "Schema for EQ info.json files",
  "type": "object",
  "properties": {
    "product_id": {
      "type": "string",
      "description": "The product ID. This is present in data dumps, but not in the database structure that humans maintain in github"
    },
    "author": {
      "type": "string",
      "description": "The author of the EQ curve. Please keep this consistent across the author's output.",
      "minLength": 1
    },
    "details": {
      "type": "string",
      "description": "Any additional information needed to understand this EQ curve, e.g. 'Harman Target • Standard' or 'Measured by John Smith'. Present segmented information using the • character (U+2022).",
      "minLength": 1
    },
    "link": {
      "type": "string",
      "description": "A link to the source, if applicable.",
      "format": "uri"
    },
    "type": {
      "type": "string",
      "description": "The type of the EQ. Currently, only 'parametric_eq' is supported. Additional types (e.g. 'graphic_eq') may be added in the future.",
      "enum": ["parametric_eq"],
      "default": "parametric_eq"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "gain_db": {
          "type": "number",
          "description": "An overall gain adjustment to apply as part of equalization.",
          "default": 0.0
        },
        "bands": {
          "type": "array",
          "description": "The parametric EQ bands, sorted by priority. Software that supports a limited number of bands should truncate the list.",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "description": "The equalizer element type.",
                "enum": [
                  "peak_dip", "high_shelf", "low_shelf", 
                  "low_pass", "high_pass", "band_pass", "band_stop"
                ]
              },
              "frequency": {
                "type": "number",
                "description": "The center frequency of the filter in Hz."
              },
              "gain_db": {
                "type": "number",
                "description": "The gain at the center frequency, in dB.",
                "default": 0.0
              },
              "q": {
                "type": "number",
                "description": "The Q value for the band, which determines the width of the filter in the frequency domain.",
                "minimum": 0.1
              },
              "slope": {
                "type": "number",
                "description": "The slope of the filter in dB/Octave, used for low_pass and high_pass filters.",
                "enum": [6, 12, 18, 24, 30, 36],
                "default": 12
              }
            },
            "required": ["type", "frequency"],
            "oneOf": [
              {
                "properties": {
                  "type": { "enum": ["low_pass", "high_pass"] },
                  "slope": { "type": "number" }
                },
                "required": ["slope"]
              },
              {
                "properties": {
                  "type": { "enum": ["peak_dip", "high_shelf", "low_shelf", "band_pass", "band_stop"] },
                  "q": { "type": "number" }
                },
                "required": ["q"]
              }
            ]
          }
        }
      },
      "required": ["gain_db", "bands"]
    }
  },
  "required": ["author", "type", "parameters"],
  "additionalProperties": false
}

=== opra-project/OPRA/database/vendors/jbl/products/tour_one_m2/eq/autoeq_filk_passive/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Filk (passive)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -6.8,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -0.3,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 170,
        "gain_db": -14.9,
        "q": 0.58
      },
      {
        "type": "peak_dip",
        "frequency": 365,
        "gain_db": 9.7,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 4186,
        "gain_db": 6.5,
        "q": 2.22
      },
      {
        "type": "peak_dip",
        "frequency": 1569,
        "gain_db": 3.2,
        "q": 1.63
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": 0.1,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 36,
        "gain_db": -0.5,
        "q": 2.43
      },
      {
        "type": "peak_dip",
        "frequency": 55,
        "gain_db": 0.7,
        "q": 2.85
      },
      {
        "type": "peak_dip",
        "frequency": 7418,
        "gain_db": -1.1,
        "q": 5.47
      },
      {
        "type": "peak_dip",
        "frequency": 69,
        "gain_db": -0.7,
        "q": 5.05
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/focal/products/azurys/eq/autoeq_oratory1990/info.json
{
  "author": "AutoEQ",
  "details": "Measured by oratory1990",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -3.9,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -3.1,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 185,
        "gain_db": -1.3,
        "q": 0.78
      },
      {
        "type": "peak_dip",
        "frequency": 9293,
        "gain_db": 2.5,
        "q": 1.66
      },
      {
        "type": "peak_dip",
        "frequency": 4836,
        "gain_db": 3.9,
        "q": 2.99
      },
      {
        "type": "peak_dip",
        "frequency": 3460,
        "gain_db": -2.8,
        "q": 3.99
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -0.7,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 1331,
        "gain_db": 1.5,
        "q": 1.61
      },
      {
        "type": "peak_dip",
        "frequency": 519,
        "gain_db": -0.6,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 74,
        "gain_db": 0.7,
        "q": 2.61
      },
      {
        "type": "peak_dip",
        "frequency": 39,
        "gain_db": -0.4,
        "q": 1.54
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/agasound/products/aga_one/eq/autoeq_tonedeafmonk/info.json
{
  "author": "AutoEQ",
  "details": "Measured by ToneDeafMonk",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -3.7,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -1.1,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 803,
        "gain_db": 3.5,
        "q": 0.78
      },
      {
        "type": "peak_dip",
        "frequency": 170,
        "gain_db": -3.1,
        "q": 0.89
      },
      {
        "type": "peak_dip",
        "frequency": 4576,
        "gain_db": -5.8,
        "q": 2.33
      },
      {
        "type": "peak_dip",
        "frequency": 6076,
        "gain_db": 5.4,
        "q": 3.47
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -0.2,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 2624,
        "gain_db": -1.4,
        "q": 3.59
      },
      {
        "type": "peak_dip",
        "frequency": 1614,
        "gain_db": 0.5,
        "q": 2.66
      },
      {
        "type": "peak_dip",
        "frequency": 3570,
        "gain_db": 0.8,
        "q": 4.28
      },
      {
        "type": "peak_dip",
        "frequency": 64,
        "gain_db": 0.2,
        "q": 1.9
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/etymotic/products/er3xr/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -8.8,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 100,
        "gain_db": 6,
        "q": 0.6
      },
      {
        "type": "peak_dip",
        "frequency": 200,
        "gain_db": -3.2,
        "q": 0.4
      },
      {
        "type": "peak_dip",
        "frequency": 1050,
        "gain_db": 3.6,
        "q": 0.9
      },
      {
        "type": "peak_dip",
        "frequency": 1350,
        "gain_db": -4.2,
        "q": 1.3
      },
      {
        "type": "peak_dip",
        "frequency": 2600,
        "gain_db": -0.6,
        "q": 1.7
      },
      {
        "type": "high_shelf",
        "frequency": 3200,
        "gain_db": 6,
        "q": 0.71
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -2,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 7000,
        "gain_db": 3.5,
        "q": 1.4
      },
      {
        "type": "peak_dip",
        "frequency": 4700,
        "gain_db": -1,
        "q": 2
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/moondrop/products/starfield_2/eq/autoeq_super_review_bass_plug/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Super Review (bass plug)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -2.8,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 0.3,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 792,
        "gain_db": 3,
        "q": 0.8
      },
      {
        "type": "peak_dip",
        "frequency": 172,
        "gain_db": -2.8,
        "q": 0.84
      },
      {
        "type": "peak_dip",
        "frequency": 4597,
        "gain_db": -3.1,
        "q": 2.59
      },
      {
        "type": "peak_dip",
        "frequency": 6209,
        "gain_db": 3.1,
        "q": 5.1
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -1.1,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 1968,
        "gain_db": 0.5,
        "q": 3.88
      },
      {
        "type": "peak_dip",
        "frequency": 62,
        "gain_db": 0.2,
        "q": 1.9
      },
      {
        "type": "peak_dip",
        "frequency": 1298,
        "gain_db": -0.3,
        "q": 3.62
      },
      {
        "type": "peak_dip",
        "frequency": 2718,
        "gain_db": -0.3,
        "q": 4.31
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/nad/products/viso_hp70/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "link": "https://www.dropbox.com/s/3mi1qsqopayh5ws/NAD%20Viso%20HP70.pdf?dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -4.5,
    "bands": [
      {
        "type": "peak_dip",
        "frequency": 28,
        "gain_db": 4.5,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 70,
        "gain_db": -0.7,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 100,
        "gain_db": -1.8,
        "q": 2.5
      },
      {
        "type": "peak_dip",
        "frequency": 200,
        "gain_db": -1.3,
        "q": 2.5
      },
      {
        "type": "peak_dip",
        "frequency": 310,
        "gain_db": 2.2,
        "q": 1.5
      },
      {
        "type": "peak_dip",
        "frequency": 1250,
        "gain_db": -2.2,
        "q": 2.5
      },
      {
        "type": "peak_dip",
        "frequency": 2200,
        "gain_db": 3.6,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 4300,
        "gain_db": -3.5,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 6920,
        "gain_db": -2.3,
        "q": 5
      },
      {
        "type": "peak_dip",
        "frequency": 7250,
        "gain_db": -2,
        "q": 9
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/qdc/products/anole_v14/eq/autoeq_crinacle_off_off_off_off/info.json
{
  "author": "AutoEQ",
  "details": "Measured by crinacle (off-off-off-off)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -4.5,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -1.2,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 167,
        "gain_db": -2.9,
        "q": 0.89
      },
      {
        "type": "peak_dip",
        "frequency": 2706,
        "gain_db": 4.8,
        "q": 0.65
      },
      {
        "type": "peak_dip",
        "frequency": 1634,
        "gain_db": -4.9,
        "q": 1.09
      },
      {
        "type": "peak_dip",
        "frequency": 681,
        "gain_db": 1.1,
        "q": 0.8
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -0.9,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 9731,
        "gain_db": -0.9,
        "q": 2.31
      },
      {
        "type": "peak_dip",
        "frequency": 5235,
        "gain_db": 2.9,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 4385,
        "gain_db": -1.9,
        "q": 5.5
      },
      {
        "type": "peak_dip",
        "frequency": 2847,
        "gain_db": 0.9,
        "q": 6
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/sennheiser/products/cx_400bt_true_wireless/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -10.9,
    "bands": [
      {
        "type": "peak_dip",
        "frequency": 190,
        "gain_db": -3.7,
        "q": 0.5
      },
      {
        "type": "peak_dip",
        "frequency": 700,
        "gain_db": 1.1,
        "q": 0.6
      },
      {
        "type": "peak_dip",
        "frequency": 1650,
        "gain_db": -5,
        "q": 1.2
      },
      {
        "type": "peak_dip",
        "frequency": 3900,
        "gain_db": 12,
        "q": 0.6
      },
      {
        "type": "peak_dip",
        "frequency": 7200,
        "gain_db": -5,
        "q": 3
      },
      {
        "type": "peak_dip",
        "frequency": 10200,
        "gain_db": -5.7,
        "q": 2.5
      },
      {
        "type": "peak_dip",
        "frequency": 14300,
        "gain_db": -3.7,
        "q": 2
      }
    ]
  }
}
