=== opra-project/OPRA/schemas/eq_info.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "EQ Info",
  "description": "Schema for EQ info.json files",
  "type": "object",
  "properties": {
    "product_id": {
      "type": "string",
      "description": "The product ID. This is present in data dumps, but not in the database structure that humans maintain in github"
    },
    "author": {
      "type": "string",
      "description": "The author of the EQ curve. Please keep this consistent across the author's output.",
      "minLength": 1
    },
    "details": {
      "type": "string",
      "description": "Any additional information needed to understand this EQ curve, e.g. 'Harman Target • Standard' or 'Measured by John Smith'. Present segmented information using the • character (U+2022).",
      "minLength": 1
    },
    "link": {
      "type": "string",
      "description": "A link to the source, if applicable.",
      "format": "uri"
    },
    "type": {
      "type": "string",
      "description": "The type of the EQ. Currently, only 'parametric_eq' is supported. Additional types (e.g. 'graphic_eq') may be added in the future.",
      "enum": ["parametric_eq"],
      "default": "parametric_eq"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "gain_db": {
          "type": "number",
          "description": "An overall gain adjustment to apply as part of equalization.",
          "default": 0.0
        },
        "bands": {
          "type": "array",
          "description": "The parametric EQ bands, sorted by priority. Software that supports a limited number of bands should truncate the list.",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "description": "The equalizer element type.",
                "enum": [
                  "peak_dip", "high_shelf", "low_shelf", 
                  "low_pass", "high_pass", "band_pass", "band_stop"
                ]
              },
              "frequency": {
                "type": "number",
                "description": "The center frequency of the filter in Hz."
              },
              "gain_db": {
                "type": "number",
                "description": "The gain at the center frequency, in dB.",
                "default": 0.0
              },
              "q": {
                "type": "number",
                "description": "The Q value for the band, which determines the width of the filter in the frequency domain.",
                "minimum": 0.1
              },
              "slope": {
                "type": "number",
                "description": "The slope of the filter in dB/Octave, used for low_pass and high_pass filters.",
                "enum": [6, 12, 18, 24, 30, 36],
                "default": 12
              }
            },
            "required": ["type", "frequency"],
            "oneOf": [
              {
                "properties": {
                  "type": { "enum": ["low_pass", "high_pass"] },
                  "slope": { "type": "number" }
                },
                "required": ["slope"]
              },
              {
                "properties": {
                  "type": { "enum": ["peak_dip", "high_shelf", "low_shelf", "band_pass", "band_stop"] },
                  "q": { "type": "number" }
                },
                "required": ["q"]
              }
            ]
          }
        }
      },
      "required": ["gain_db", "bands"]
    }
  },
  "required": ["author", "type", "parameters"],
  "additionalProperties": false
}

=== opra-project/OPRA/database/vendors/lz_hi_fi_audio/products/a4_pro/eq/autoeq_rikudougoku_blue_nozzle_blue_vent/info.json
{
  "author": "AutoEQ",
  "details": "Measured by RikudouGoku (blue nozzle, blue vent)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -6.6,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 5.8,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 6747,
        "gain_db": 6.2,
        "q": 2.65
      },
      {
        "type": "peak_dip",
        "frequency": 1836,
        "gain_db": -7.7,
        "q": 2.32
      },
      {
        "type": "peak_dip",
        "frequency": 184,
        "gain_db": -1.9,
        "q": 1.02
      },
      {
        "type": "peak_dip",
        "frequency": 5272,
        "gain_db": 4.3,
        "q": 4.54
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": 0.4,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 3501,
        "gain_db": -3.8,
        "q": 5.03
      },
      {
        "type": "peak_dip",
        "frequency": 727,
        "gain_db": 1.1,
        "q": 1.68
      },
      {
        "type": "peak_dip",
        "frequency": 2662,
        "gain_db": 2.2,
        "q": 4.59
      },
      {
        "type": "peak_dip",
        "frequency": 1228,
        "gain_db": -0.8,
        "q": 2.68
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/apple/products/airpods_pro_1st_gen/eq/oratory1990_usound_target/info.json
{
  "author": "oratory1990",
  "details": "USound Target",
  "link": "https://www.dropbox.com/scl/fi/0tw98j0sbhol4ruf2e4vt/Apple-AirPods-Pro-USound.pdf?rlkey=g2eekduzqj9bhr11ss9pffabq&dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -8.4,
    "bands": [
      {
        "type": "peak_dip",
        "frequency": 43,
        "gain_db": -1.8,
        "q": 1
      },
      {
        "type": "low_shelf",
        "frequency": 250,
        "gain_db": 8.5,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 600,
        "gain_db": -0.8,
        "q": 0.9
      },
      {
        "type": "peak_dip",
        "frequency": 935,
        "gain_db": 2,
        "q": 2
      },
      {
        "type": "high_shelf",
        "frequency": 3500,
        "gain_db": 8,
        "q": 0.9
      },
      {
        "type": "peak_dip",
        "frequency": 5900,
        "gain_db": -1.1,
        "q": 4
      },
      {
        "type": "high_shelf",
        "frequency": 9000,
        "gain_db": -7,
        "q": 0.71
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/beats/products/solo3/eq/autoeq_innerfidelity_2016_wireless/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Innerfidelity (2016, wireless)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -4.4,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -0.6,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 209,
        "gain_db": -6.9,
        "q": 0.5
      },
      {
        "type": "peak_dip",
        "frequency": 7293,
        "gain_db": 6.9,
        "q": 0.18
      },
      {
        "type": "peak_dip",
        "frequency": 518,
        "gain_db": 3.6,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 3879,
        "gain_db": -7.5,
        "q": 1.03
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -3.5,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 2200,
        "gain_db": 2,
        "q": 3.14
      },
      {
        "type": "peak_dip",
        "frequency": 1395,
        "gain_db": -1,
        "q": 2.33
      },
      {
        "type": "peak_dip",
        "frequency": 3421,
        "gain_db": -2.8,
        "q": 4.75
      },
      {
        "type": "peak_dip",
        "frequency": 4088,
        "gain_db": 2.6,
        "q": 6
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/simgot_audio/products/ea500/eq/autoeq_auriculares_argentina_black_nozzle/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Auriculares Argentina (black nozzle)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -6.1,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 7.6,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 73,
        "gain_db": -3.1,
        "q": 0.32
      },
      {
        "type": "peak_dip",
        "frequency": 732,
        "gain_db": 2,
        "q": 1.03
      },
      {
        "type": "peak_dip",
        "frequency": 2464,
        "gain_db": -3.3,
        "q": 1.32
      },
      {
        "type": "peak_dip",
        "frequency": 3847,
        "gain_db": 3.2,
        "q": 1.9
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -9.3,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 10000,
        "gain_db": 2.3,
        "q": 1.69
      },
      {
        "type": "peak_dip",
        "frequency": 6862,
        "gain_db": 2.6,
        "q": 2.84
      },
      {
        "type": "peak_dip",
        "frequency": 5740,
        "gain_db": -1.6,
        "q": 5.34
      },
      {
        "type": "peak_dip",
        "frequency": 1321,
        "gain_db": -0.2,
        "q": 3.77
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/xenns/products/mangird_top_pro/eq/autoeq_jaytiss/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Jaytiss",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -6,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -1.8,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 5757,
        "gain_db": 6.1,
        "q": 2.2
      },
      {
        "type": "peak_dip",
        "frequency": 304,
        "gain_db": -2,
        "q": 1.02
      },
      {
        "type": "peak_dip",
        "frequency": 1818,
        "gain_db": -1.1,
        "q": 1.84
      },
      {
        "type": "peak_dip",
        "frequency": 803,
        "gain_db": 1.3,
        "q": 2.3
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -7.8,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 74,
        "gain_db": 0.9,
        "q": 2.19
      },
      {
        "type": "peak_dip",
        "frequency": 8502,
        "gain_db": 2.4,
        "q": 2.28
      },
      {
        "type": "peak_dip",
        "frequency": 3346,
        "gain_db": 0.9,
        "q": 3.79
      },
      {
        "type": "peak_dip",
        "frequency": 173,
        "gain_db": -0.2,
        "q": 1.53
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/beyerdynamic/products/dt_1990/eq/autoeq_rtings_balanced_earpads/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Rtings (balanced earpads)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -4.1,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 4.2,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 8280,
        "gain_db": -8.7,
        "q": 0.97
      },
      {
        "type": "peak_dip",
        "frequency": 4605,
        "gain_db": 5.3,
        "q": 2.41
      },
      {
        "type": "peak_dip",
        "frequency": 1524,
        "gain_db": 3.4,
        "q": 0.45
      },
      {
        "type": "peak_dip",
        "frequency": 172,
        "gain_db": -2.4,
        "q": 0.59
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -4.5,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 9279,
        "gain_db": 2.1,
        "q": 2.61
      },
      {
        "type": "peak_dip",
        "frequency": 2170,
        "gain_db": 1.1,
        "q": 4.69
      },
      {
        "type": "peak_dip",
        "frequency": 3046,
        "gain_db": -0.7,
        "q": 2.46
      },
      {
        "type": "peak_dip",
        "frequency": 4133,
        "gain_db": 0.7,
        "q": 6
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/kingsound/products/ks_h04/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "link": "https://www.dropbox.com/s/5dsgvbhai1afvr6/Kingsound%20KS-H04.pdf?dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -9.5,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 38,
        "gain_db": 4,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 65,
        "gain_db": -1.1,
        "q": 1.4
      },
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 5.5,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 990,
        "gain_db": -5.2,
        "q": 2.5
      },
      {
        "type": "high_shelf",
        "frequency": 1400,
        "gain_db": 6,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 1500,
        "gain_db": -2.7,
        "q": 2.7
      },
      {
        "type": "peak_dip",
        "frequency": 3400,
        "gain_db": -1.3,
        "q": 4
      },
      {
        "type": "peak_dip",
        "frequency": 4700,
        "gain_db": -1.5,
        "q": 4
      },
      {
        "type": "peak_dip",
        "frequency": 8400,
        "gain_db": -4,
        "q": 6
      },
      {
        "type": "high_shelf",
        "frequency": 11000,
        "gain_db": -10,
        "q": 0.71
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/stax/products/sr_5_gold/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "link": "https://www.dropbox.com/s/vzfx5kw28r64gac/Stax%20SR-5%20Gold.pdf?dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -7.2,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 85,
        "gain_db": 6,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 210,
        "gain_db": -1.4,
        "q": 1.1
      },
      {
        "type": "high_shelf",
        "frequency": 1000,
        "gain_db": 7,
        "q": 0.71
      },
      {
        "type": "peak_dip",
        "frequency": 1025,
        "gain_db": -4.1,
        "q": 2.5
      },
      {
        "type": "peak_dip",
        "frequency": 1800,
        "gain_db": 0.7,
        "q": 3
      },
      {
        "type": "peak_dip",
        "frequency": 2870,
        "gain_db": -9.1,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 5480,
        "gain_db": -8.6,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 6800,
        "gain_db": 2.5,
        "q": 3
      },
      {
        "type": "peak_dip",
        "frequency": 8700,
        "gain_db": -3.5,
        "q": 6
      },
      {
        "type": "high_shelf",
        "frequency": 12000,
        "gain_db": -10,
        "q": 0.71
      }
    ]
  }
}
