=== opra-project/OPRA/schemas/eq_info.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "EQ Info",
  "description": "Schema for EQ info.json files",
  "type": "object",
  "properties": {
    "product_id": {
      "type": "string",
      "description": "The product ID. This is present in data dumps, but not in the database structure that humans maintain in github"
    },
    "author": {
      "type": "string",
      "description": "The author of the EQ curve. Please keep this consistent across the author's output.",
      "minLength": 1
    },
    "details": {
      "type": "string",
      "description": "Any additional information needed to understand this EQ curve, e.g. 'Harman Target • Standard' or 'Measured by John Smith'. Present segmented information using the • character (U+2022).",
      "minLength": 1
    },
    "link": {
      "type": "string",
      "description": "A link to the source, if applicable.",
      "format": "uri"
    },
    "type": {
      "type": "string",
      "description": "The type of the EQ. Currently, only 'parametric_eq' is supported. Additional types (e.g. 'graphic_eq') may be added in the future.",
      "enum": ["parametric_eq"],
      "default": "parametric_eq"
    },
    "parameters": {
      "type": "object",
      "properties": {
        "gain_db": {
          "type": "number",
          "description": "An overall gain adjustment to apply as part of equalization.",
          "default": 0.0
        },
        "bands": {
          "type": "array",
          "description": "The parametric EQ bands, sorted by priority. Software that supports a limited number of bands should truncate the list.",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "description": "The equalizer element type.",
                "enum": [
                  "peak_dip", "high_shelf", "low_shelf", 
                  "low_pass", "high_pass", "band_pass", "band_stop"
                ]
              },
              "frequency": {
                "type": "number",
                "description": "The center frequency of the filter in Hz."
              },
              "gain_db": {
                "type": "number",
                "description": "The gain at the center frequency, in dB.",
                "default": 0.0
              },
              "q": {
                "type": "number",
                "description": "The Q value for the band, which determines the width of the filter in the frequency domain.",
                "minimum": 0.1
              },
              "slope": {
                "type": "number",
                "description": "The slope of the filter in dB/Octave, used for low_pass and high_pass filters.",
                "enum": [6, 12, 18, 24, 30, 36],
                "default": 12
              }
            },
            "required": ["type", "frequency"],
            "oneOf": [
              {
                "properties": {
                  "type": { "enum": ["low_pass", "high_pass"] },
                  "slope": { "type": "number" }
                },
                "required": ["slope"]
              },
              {
                "properties": {
                  "type": { "enum": ["peak_dip", "high_shelf", "low_shelf", "band_pass", "band_stop"] },
                  "q": { "type": "number" }
                },
                "required": ["q"]
              }
            ]
          }
        }
      },
      "required": ["gain_db", "bands"]
    }
  },
  "required": ["author", "type", "parameters"],
  "additionalProperties": false
}

=== opra-project/OPRA/database/vendors/moondrop/products/starfield/eq/oratory1990_crinacle_target/info.json
{
  "author": "oratory1990",
  "details": "crinacle target",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": 0.1,
    "bands": [
      {
        "type": "peak_dip",
        "frequency": 27,
        "gain_db": -8.4,
        "q": 0.18
      },
      {
        "type": "peak_dip",
        "frequency": 1060,
        "gain_db": -1,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 2600,
        "gain_db": -2.5,
        "q": 1.2
      },
      {
        "type": "peak_dip",
        "frequency": 4600,
        "gain_db": -1.9,
        "q": 2.7
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/noble_audio/products/k10_ciem/eq/oratory1990_oratory1990_target/info.json
{
  "author": "oratory1990",
  "details": "oratory1990 Target",
  "link": "https://www.dropbox.com/s/nvd0u03f8ixke4l/Noble%20K10%20CIEM%20%28oratory1990%20target%29.pdf?dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -5,
    "bands": [
      {
        "type": "peak_dip",
        "frequency": 250,
        "gain_db": -3.7,
        "q": 0.45
      },
      {
        "type": "peak_dip",
        "frequency": 800,
        "gain_db": 3,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 1430,
        "gain_db": -5.9,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 2500,
        "gain_db": -3.2,
        "q": 1.5
      },
      {
        "type": "peak_dip",
        "frequency": 3270,
        "gain_db": -2.2,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 4000,
        "gain_db": 8,
        "q": 0.8
      },
      {
        "type": "peak_dip",
        "frequency": 5420,
        "gain_db": -13.2,
        "q": 3
      },
      {
        "type": "peak_dip",
        "frequency": 6000,
        "gain_db": 4,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 9400,
        "gain_db": -4,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 11350,
        "gain_db": -6.7,
        "q": 4
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/jlab_audio/products/jbuds_lux_anc/eq/oratory1990_harman_target/info.json
{
  "author": "oratory1990",
  "details": "Harman Target",
  "link": "https://www.dropbox.com/scl/fi/3v9l64qlplhafu3zl629p/JLab-JBuds-Lux-ANC.pdf?rlkey=75i137ul8d35kyv7qhepfmmi1&dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -1.6,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 0,
        "q": 0.71
      },
      {
        "type": "low_shelf",
        "frequency": 380,
        "gain_db": -3,
        "q": 0.9
      },
      {
        "type": "peak_dip",
        "frequency": 600,
        "gain_db": 1.7,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 890,
        "gain_db": -1.5,
        "q": 3.5
      },
      {
        "type": "peak_dip",
        "frequency": 2400,
        "gain_db": 4,
        "q": 1.4
      },
      {
        "type": "high_shelf",
        "frequency": 2500,
        "gain_db": -5,
        "q": 0.35
      },
      {
        "type": "peak_dip",
        "frequency": 3250,
        "gain_db": -1.8,
        "q": 4
      },
      {
        "type": "peak_dip",
        "frequency": 4900,
        "gain_db": 2,
        "q": 2
      },
      {
        "type": "peak_dip",
        "frequency": 6000,
        "gain_db": -4.2,
        "q": 5
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": 5,
        "q": 0.71
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/hidition/products/viento/eq/autoeq_crinacle_bass_mids/info.json
{
  "author": "AutoEQ",
  "details": "Measured by crinacle (bass, mids)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -3.7,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 1.2,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 229,
        "gain_db": -2.6,
        "q": 0.56
      },
      {
        "type": "peak_dip",
        "frequency": 5006,
        "gain_db": 3.5,
        "q": 1.17
      },
      {
        "type": "peak_dip",
        "frequency": 71,
        "gain_db": 1.5,
        "q": 1.07
      },
      {
        "type": "peak_dip",
        "frequency": 948,
        "gain_db": 2.3,
        "q": 2.31
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -6,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 10000,
        "gain_db": 5.1,
        "q": 1.6
      },
      {
        "type": "peak_dip",
        "frequency": 6815,
        "gain_db": -2.6,
        "q": 5.98
      },
      {
        "type": "peak_dip",
        "frequency": 3068,
        "gain_db": -1.1,
        "q": 5.03
      },
      {
        "type": "peak_dip",
        "frequency": 3731,
        "gain_db": 0.6,
        "q": 6
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/sennheiser/products/hd_650/eq/autoeq_crinacle_2020_worn_earpads/info.json
{
  "author": "AutoEQ",
  "details": "Measured by crinacle (2020, worn earpads)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -6.3,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": 6.8,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 9243,
        "gain_db": 5.8,
        "q": 0.21
      },
      {
        "type": "peak_dip",
        "frequency": 122,
        "gain_db": -3.6,
        "q": 0.45
      },
      {
        "type": "peak_dip",
        "frequency": 2969,
        "gain_db": -4.3,
        "q": 2.34
      },
      {
        "type": "peak_dip",
        "frequency": 1321,
        "gain_db": -3.2,
        "q": 0.99
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -2.4,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 5093,
        "gain_db": 1.6,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 6455,
        "gain_db": -1,
        "q": 6
      },
      {
        "type": "peak_dip",
        "frequency": 84,
        "gain_db": -0.4,
        "q": 3.62
      },
      {
        "type": "peak_dip",
        "frequency": 137,
        "gain_db": 0.3,
        "q": 2.52
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/sennheiser/products/hd_490_pro/eq/rtings_target_senselab_aizu_parametric_5band/info.json
{
  "author": "Rtings/AutoEQ",
  "details": "Target_SenseLab_Aizu",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -5.8,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 38.0,
        "gain_db": 6.6,
        "q": 0.65
      },
      {
        "type": "peak_dip",
        "frequency": 4223.0,
        "gain_db": -4.8,
        "q": 2.85
      },
      {
        "type": "peak_dip",
        "frequency": 1856.0,
        "gain_db": 2.0,
        "q": 2.77
      },
      {
        "type": "peak_dip",
        "frequency": 847.0,
        "gain_db": 1.4,
        "q": 1.87
      },
      {
        "type": "peak_dip",
        "frequency": 343.0,
        "gain_db": -0.6,
        "q": 1.63
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/kz/products/zs7/eq/oratory1990_usound_target_preliminary/info.json
{
  "author": "oratory1990",
  "details": "USound Target • preliminary",
  "link": "https://www.dropbox.com/s/dvboobclj6emhwy/KZ%20ZS7%20%28USound%20Target%29.pdf?dl=0",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": 0,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 158,
        "gain_db": 10,
        "q": 0.65
      },
      {
        "type": "peak_dip",
        "frequency": 50,
        "gain_db": -13.4,
        "q": 0.17
      },
      {
        "type": "peak_dip",
        "frequency": 780,
        "gain_db": 1.8,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 2330,
        "gain_db": -8.3,
        "q": 1.9
      },
      {
        "type": "high_shelf",
        "frequency": 3000,
        "gain_db": 6,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 4050,
        "gain_db": -7.5,
        "q": 3
      },
      {
        "type": "high_shelf",
        "frequency": 7000,
        "gain_db": -8,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 1375,
        "gain_db": -1.3,
        "q": 2.5
      }
    ]
  }
}

=== opra-project/OPRA/database/vendors/simgot_audio/products/ea500lm/eq/autoeq_harpo_bronze_nozzle/info.json
{
  "author": "AutoEQ",
  "details": "Measured by Harpo (bronze nozzle)",
  "type": "parametric_eq",
  "parameters": {
    "gain_db": -2.2,
    "bands": [
      {
        "type": "low_shelf",
        "frequency": 105,
        "gain_db": -1.4,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 703,
        "gain_db": 2.4,
        "q": 1
      },
      {
        "type": "peak_dip",
        "frequency": 177,
        "gain_db": -2,
        "q": 1.03
      },
      {
        "type": "peak_dip",
        "frequency": 63,
        "gain_db": 0.9,
        "q": 1.43
      },
      {
        "type": "peak_dip",
        "frequency": 2622,
        "gain_db": -1.2,
        "q": 2.7
      },
      {
        "type": "high_shelf",
        "frequency": 10000,
        "gain_db": -2.1,
        "q": 0.7
      },
      {
        "type": "peak_dip",
        "frequency": 8554,
        "gain_db": 1.9,
        "q": 3.53
      },
      {
        "type": "peak_dip",
        "frequency": 6048,
        "gain_db": 1.4,
        "q": 5.06
      },
      {
        "type": "peak_dip",
        "frequency": 4781,
        "gain_db": -0.8,
        "q": 5.16
      },
      {
        "type": "peak_dip",
        "frequency": 1470,
        "gain_db": -0.1,
        "q": 2.19
      }
    ]
  }
}
